language: java
# to make the build work with oraclejdk8: https://travis-ci.community/t/solved-oraclejdk8-installation-failing-still-again/3428
dist: trusty
jdk: oraclejdk8
services:
  - xvfb
before_install:
  - sudo apt update
  - chmod +x ./gradlew
  - export DISPLAY=:99.0
install: true
before_cache:
  - rm -f $HOME/.gradle/caches/modules-2/modules-2.lock
cache:
  directories:
  - $HOME/.m2/
  - $HOME/.gradle/caches/
  - $HOME/.gradle/wrapper/
before_script:
  - ./gradlew --version
script: ./gradlew build -S
env: TERM=dumb
